#:schema .dprint.schema.json

excludes = ["docs/rfc/**", "research/htmlrewrite/guest/vendor/lol_html/**"]
plugins  = [
  "npm:@dprint/dockerfile@0.6.0",
  "npm:dprint-plugin-markup@0.27.5",
  "npm:dprint-plugin-yaml@0.6.0",
  "npm:@dprint/json@0.25.0",
  "https://plugins.dprint.dev/kjanat/svg-v0.4.1.wasm",
  "npm:@dprint/markdown@0.24.0",
  "npm:@jakebailey/dprint-plugin-gofumpt@0.0.18",
  "npm:@dprint/typescript@0.96.1",
  "npm:@dprint/exec@0.7.3/plugin.json",
  "https://plugins.dprint.dev/kjanat/shfmt-1.1.1.wasm"
]

[markup]
associations = ["!**/*.svg"]

[yaml]
printWidth = 160

[svg]
associations = ["**/*.svg"]

[gofumpt]
langVersion = "go1.27"
modulePath  = "statute.kjanat.dev"

[gofumpt.extra]
groupParams = true

[typescript]
useTabs    = true
quoteStyle = "preferSingle"

[[markdown.overrides]]
files     = ["CHANGELOG.md"]
textWrap  = "always"
lineWidth = 99999

[shfmt]
useTabs          = true
binaryNextLine   = true
switchCaseIndent = true

[exec]
cwd = "${configDir}"

[[exec.commands]]
command       = "go tool goimports -local statute.kjanat.dev"
exts          = ["go"]
cacheKeyFiles = ["go.mod"]

[[exec.commands]]
command       = "gofmt -s"
exts          = ["go"]
cacheKeyFiles = ["go.mod"]

[[exec.commands]]
command       = "tombi format - --stdin-filename {{file_path}}"
exts          = ["toml"]
cacheKeyFiles = ["tombi.toml", ".mise.toml"]
