#:schema https://mise.jdx.dev/schema/mise.json
#:tombi toml-version = "v1.1.0"

[tools]
go         = "latest"
node       = "26"
shellcheck = "latest"
runner-run = { version = "0.27.1", filter_bins = ["run", "runner"] }
tombi      = "1.7.3"

[tools.actionlint]
prerelease          = true
version             = "latest"
minimum_release_age = "0s"
depends             = ["shellcheck"]
lazy                = true

[tools.binaryen]
version        = "133"
version_prefix = "version_"
filter_bins    = ["wasm-opt"]

[tools.dprint]
prerelease          = true
version             = "latest"
minimum_release_age = "0s"
rename_exe          = "kprint"
postinstall         = "kprint"
depends             = ["tombi", "go"]
tag_regex           = '^\d+\.\d+\.\d+.kjanat$'

[tools."golangci-lint"]
version = "2.14.0"
depends = ["go"]

[tool_alias]
actionlint = "go:actionlint.kjanat.dev/cmd/actionlint"
binaryen   = "github:WebAssembly/binaryen"
dprint     = "github:kjanat/dprint"
runner-run = "github:kjanat/runner"
shellcheck = "github:koalaman/shellcheck"
tombi      = "github:tombi-toml/tombi"

[settings]
idiomatic_version_file_enable_tools = ["go"]
minimum_release_age                 = "0s"
prereleases                         = true
experimental                        = true

[bootstrap.repos]
wiki = { url = "https://github.com/kjanat/statute.wiki.git" }

# [tasks.actionlint]
# # run = {}
[deps.npm]
auto = true
run  = "npm ci --no-audit --no-fund"
