#:schema https://mise.jdx.dev/schema/mise.json
#:tombi toml-version = "v1.1.0"

[tools]
go   = "latest"
node = "latest"
npm  = "12"

[tools."github:microsoft/TypeScript"]
version = "7.0.2"

[tools."go:actionlint.kjanat.dev/cmd/actionlint"]
prerelease          = true
version             = "master"
minimum_release_age = "0s"
depends             = ["github:koalaman/shellcheck"]
lazy                = true

[tools."github:WebAssembly/binaryen"]
version        = "133"
version_prefix = "version_"
filter_bins    = ["wasm-opt"]

[tools."github:kjanat/dprint"]
prerelease          = true
version             = "latest"
minimum_release_age = "0s"
rename_exe          = "kprint"
postinstall         = "kprint"
depends             = ["github:tombi-toml/tombi", "go"]

[tools."golangci-lint"]
version = "2.14.0"
depends = ["go"]

[tools."github:kjanat/runner"]
version = "0.27.1"

[tools."github:tombi-toml/tombi"]
version = "1.7.3"

[tools."github:koalaman/shellcheck"]
version = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go", "node"]
node.npm_shim                       = true
minimum_release_age                 = "0s"
minimum_release_age_excludes        = ["github:kjanat/dprint"]
prereleases                         = true
experimental                        = true

[bootstrap.repos]
wiki = { url = "https://github.com/kjanat/statute.wiki.git" }

# [tasks.actionlint]
# # run = {}
[deps.npm]
auto = true
run  = "npm ci --no-audit --no-fund"

[shell_alias]
dprint = "kprint"
