[package]
name    = "statute-htmlrewrite-spike"
version = "0.0.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lol_html = { path = "vendor/lol_html", version = "=3.0.1" }

[dev-dependencies]
upstream_lol_html = { package = "lol_html", version = "=3.0.1" }

[profile.release]
opt-level = 3
strip     = true
lto       = true
panic     = "abort"
